language: node_js
node_js:
  - 12
  - 10

services:
  - docker
  
before_install: 
  - wget https://github.com/jwilder/dockerize/releases/download/v0.6.1/dockerize-linux-amd64-v0.6.1.tar.gz -O /tmp/dockerize.tar.gz
  - sudo tar -C /usr/local/bin -xzvf /tmp/dockerize.tar.gz

before_script:
  - sudo service mysql stop
  - sudo service postgresql stop
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USER" --password-stdin;
  - docker-compose --compatibility up -d
  - cp ormconfig.travis.json ormconfig.json

script:
  - bash show_memory.sh &
  - npm run lint
  - dockerize -wait tcp://localhost:39041 -timeout 15m
  - sleep 7m
  - sleep 7m
  - npx nyc npm test

after_success:
  - bash <(curl -s https://codecov.io/bash)
