language: node_js
node_js:
  - 13
  - 12
  - 10

services:
  - docker

before_script:
  - sudo service mysql stop
  - sudo service postgresql stop
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USER" --password-stdin;
  - docker-compose up -d
  - cp ormconfig.travis.json ormconfig.json

script:
  - npm run lint
  - dockerize -wait tcp://localhost:39017 -timeout 15m
  - npx nyc npm test

after_success:
  - bash <(curl -s https://codecov.io/bash)
