version: '3'
services:

 
  # sap hana (works only on linux)
  hanaexpress:
    image: "store/saplabs/hanaexpress:2.00.040.00.20190729.1"
    deploy:
      resources:
        limits:
          memory: 6500m
    container_name: "typeorm-hanaexpress"
    hostname: hxe
    command: ['--passwords-url', 'https://raw.githubusercontent.com/typeorm/typeorm/b119f7c3b8748aea9c77c7bc42b8e1be209b43ec/docker/hana/hxe-config.json', '--agree-to-sap-license']
    ulimits:
      nofile: 1048576
    sysctls:
      - kernel.shmmax=1073741824
      - net.ipv4.ip_local_port_range=40000 60999
      - kernel.shmmni=524288
      - kernel.shmall=8388608
    ports:
      - 39013:39013
      - 39017:39017
      - 39041-39045:39041-39045
      - 1128-1129:1128-1129
      - 59013-59014:59013-59014

  # redis
  # redis:
  #   image: "redis:3.0.3"
  #   container_name: "typeorm-redis"
  #   ports:
  #     - "6379:6379"

